#!/bin/bash
# Coloring
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

#Checking Required Pakcages
echo -e "${YELLOW}Checking Required packages${NOCOLOR}"

packages=("wget" "zip" "unzip" "curl" "x11-repo" "qemu-system-i386" "qemu-user-i386" "jq" "libandroid-wordexp")

for pkg in ${packages[@]}; do

    is_pkg_installed=$(dpkg-query -W --showformat='${Status}\n' ${pkg} | grep "install ok installed")

    if [ "${is_pkg_installed}" == "install ok installed" ]; then
        echo -e ${GREEN}${pkg}${NOCOLOR} is installed.
    else [ "" = "${is_pkg_installed}" ];
     echo -e "${RED}No ${pkg}. Setting up ${pkg}.${NOCOLOR}" 
    pkg install ${pkg} -y
    fi
done